/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LinkableTitle {
        /**
          * Position of icon
         */
        "iconPosition": 'start' | 'end';
        /**
          * If there's an icon to be displayed on hover/focus
         */
        "noIcon": boolean;
        /**
          * HTML tag to be used for the content
         */
        "tag": string;
    }
}
declare global {
    interface HTMLLinkableTitleElement extends Components.LinkableTitle, HTMLStencilElement {
    }
    var HTMLLinkableTitleElement: {
        prototype: HTMLLinkableTitleElement;
        new (): HTMLLinkableTitleElement;
    };
    interface HTMLElementTagNameMap {
        "linkable-title": HTMLLinkableTitleElement;
    }
}
declare namespace LocalJSX {
    interface LinkableTitle {
        /**
          * Position of icon
         */
        "iconPosition"?: 'start' | 'end';
        /**
          * If there's an icon to be displayed on hover/focus
         */
        "noIcon"?: boolean;
        /**
          * HTML tag to be used for the content
         */
        "tag"?: string;
    }
    interface IntrinsicElements {
        "linkable-title": LinkableTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "linkable-title": LocalJSX.LinkableTitle & JSXBase.HTMLAttributes<HTMLLinkableTitleElement>;
        }
    }
}
